### ISSUE TITLE
怎么加上 NSLocalizedString 的注释呢？

### ISSUE THREAD

**Issue by Raysonly** [FateOfKing/macShell#1]
我想在 localized_xxx 后面加上 NSLocalizedString的注释，需要怎么改脚本呢？

**Comment by keven-one** [comment]
修改`sed "s/\" = \".*$/;/g" ${localizableFile} | sed "s/.*/& &/" | sed "s/^\"/ #define localized_/g" | sed "s/; \"/ localized(@\"/g" | sed "s/;/\")/g" > "${localizedFile}.tmp"`这句话，具体怎么改建议你学一下shell的sed语法，不难。自己动手丰衣足食！

**Comment by Raysonly** [comment]
已经改好了，很好用，感谢分享。
